### ISSUE TITLE
Suggestion: Do not return channel id in webhook post back

### ISSUE THREAD

**Issue by EFF** [botpress/messaging#101]
**Currently**: When we capture a user's message in the webhook we receive something like the following
```
{
 channelId: 'asdasdas',
 clientId: 'asdasd',
 /*....*/
}
```

Then if you want to reply to that message you need to specify the channel and no where it says that we should use the channel name and not the id which can become confusing.  It's also super tempting to use `data.channel`.

From what I understand, channel-id is for internal usage so it shouldn't be exposed to the user

**Comment by samuelmasse** [comment]
Agreed. Channel id is for internal usage so sending it to the api user is pretty confusing. It would also be better not to have to supply the channel name at all when making a reply (which should be possible to implement pretty easily).
