### ISSUE TITLE
Database Map

### ISSUE THREAD

**Issue by allardy** [botpress/messaging#17]
There is a lot of new tables. 
Can you make a database schema explaining the link between them, their purpose, and the source of the information? This schema could grow over time and would be very useful to understand the flow of information for new users (ex: me)

Ex: 
![image](https://user-images.githubusercontent.com/42552874/125814626-1cc6c093-0f53-4efb-a064-c14ef2162ad2.png)

**Comment by samuelmasse** [comment]
https://github.com/botpress/messaging/blob/master/doc/database.md
