### ISSUE TITLE
Cannot build repository

### ISSUE THREAD

**Issue by allardy** [botpress/messaging#170]
I know that repositories should have more autonomy, but they should still be able to be built together with all other repositories. I don't think we have a lot of clients who are able to install multiple versions of nodejs on their development computer just because we have different requirements.

I am simply unable to build everything without messing around with node versions (.nvmrc is not supported on windows). Therefore, It makes more sense to stick to the same node version for all related repositories. 

Either you find a way to scale down the version requirement of messaging to the version we use everywhere else (including the builtin server in the binary), or you find a way to update the version in each repositories at the same time (including related tests).

At first glance, the module `eslint-plugins-jsdoc` version 36 requires a higher node version, is there any reason for that ? Can't we simply use the same version we have everywhere else and skip this requirement?

Apart from that, there is also an higher requirement for "parcel". What is this package used for? If it's for frontend, why not using webpack like every other repositories we have ?

Having independence over the codebase doesn't mean that you have to reinvent the wheel and to make things incompatible between other codebases, we should be able to work seamless between workspaces 

![image](https://user-images.githubusercontent.com/42552874/132808401-481a7dfd-f6c9-4870-9382-d729df328b6a.png)

**Comment by allardy** [comment]
Parcel is only used for an internal dev tool... Can you use version 1.12.4 instead ? Or make it an optional build... We have a different node version specifically in this repo only for that purpose

**Comment by samuelmasse** [comment]
We can change the version to 12.13.0 no problem. Parcel and eslint-plugins-jsdoc should work fine.

We use parcel instead of webpack because it requires 0 configuration and doesn't need any plugins. Getting the same result with webpack would have required 3-4 plugins, a ~100 lines of config and the web-pack-dev-server for hot reloading.
