### ISSUE TITLE
[BUG] Web Channel | Voice Composer

### ISSUE THREAD

**Issue by bassamtantawi-botpress** [botpress/messaging#173]
v12.26.1

I was trying to use the voice composer after activating the google speech module, and I face the below issue in the logs:

09/13/2021 23:03:35.996 Mod[channel-web] [test]
                                HTTP (post) URL /media
                                Received "This type of file is not allowed: audio/webm"
                                Request failed with status code 400

**Comment by samuelmasse** [comment]
This should be in https://github.com/botpress/botpress
