### ISSUE TITLE
[BUG] Switching messaging endpoints causes massive DDOS between services

### ISSUE THREAD

**Issue by allardy** [botpress/messaging#183]
So hm, if you simply change the messaging endpoint and restart the server, when you open the webchat there's a ton of endless queries. This definitely would need some sort of protection to prevent a user to ddos the service

1. Download botpress v12.26.1
2. Create a bot (welcome-bot)
3. Download messaging v0.1.13 from the official release
4. Start the process
3. Set MESSAGING_ENDPOINT and restart botpress. This happens:

![image](https://user-images.githubusercontent.com/42552874/135341796-f22c9f62-f1e1-4bcf-9de6-73f18d1046fe.png)

If you create a bot with a remote endpoint and then remove it, it does the same thing locally
![image](https://user-images.githubusercontent.com/42552874/135342551-af2b2708-e104-459b-a661-7760854b097b.png)

**Comment by laurentlp** [comment]
Temporary workaround is to delete the `bp/socket/studio/user` key in your local storage.
