### ISSUE TITLE
[FEATURE] WhatsApp interactive message templates

### ISSUE THREAD

**Issue by hacheybj** [botpress/messaging#187]
`WhatsApp` now supports interactive messages (`buttons`)!

This should be supported rather than resorting to the old way of sending the options in as a text message.

https://developers.facebook.com/docs/whatsapp/guides/interactive-messages

**Comment by samuelmasse** [comment]
@hacheybj Yes we'll need to have a new version of our smooch channel that runs on their v2 api while still supporting our old channel. This is doable but not the highest priority right now. So we'll probably have this in a couple of months

**Comment by samuelmasse** [comment]
Hey @hacheybj. Smooch was upgraded to v2 and vonage was upgraded from v0.1 to v1 of their api. This PR  #338 upgraded the vonage channel and uses interactive messages. These new channels will be released for the cloud soon, and will be made available for standard botpress sometime after
