### ISSUE TITLE
[BUG] Sync issues

### ISSUE THREAD

**Issue by allardy** [botpress/messaging#190]
When you don't follow the "happy path", it's incredibly hard to get messaging to work.

## Creating a bot in one instance and move it elsewhere
1. Spin a standalone messaging server.
2. Spin a botpress server and set MESSAGING_ENDPOINT to that server
3. Create a bot
4. Export the bot
5. Kill the server
6. Spin a different server, with the same messaging endpoint.
7. Import the same bot there

It should work correctly. Right now, it fails because the bot ID must be unique, but it shouldn't be the case in the future. 

## Reset messaging credentials
If you create a bot on a server, then  remove messaging.id / messaging.token, and restart the server, it will receive a new id / token combination, but it doesn't seems to update the messaging database, because the bot doesn't work anymore.

## Deleting and importing the same bot
If you export a bot, delete it, clear the id/token and re-import the bot with the same name, it will fail

**Comment by samuelmasse** [comment]
This is fixed
