### ISSUE TITLE
[BUG] Carousel cards in reverse in WhatsApp

### ISSUE THREAD

**Issue by hacheybj** [botpress/messaging#192]
**Describe the bug**
`Carousel` Cards are sent in reverse order to WhatsApp (through Smooch)

![image](https://user-images.githubusercontent.com/59566773/136261034-b0a7095a-7d4b-4eb3-92f1-1d54e71a124a.png)

**Environment (please complete the following information):**
- 12.26.4

Closes DEV-1889

**Comment by samuelmasse** [comment]
See comments on https://linear.app/botpress/issue/DEV-1889/[bug]-carousel-cards-in-reverse-in-whatsapp-botpressborpress-5546

This is a problem with smooch that isn't fixable
