### ISSUE TITLE
Mattermost Support

### ISSUE THREAD

**Issue by JustusNBB** [botpress/messaging#220]
Follow up on https://github.com/botpress/botpress/issues/788
As this now has its own project, I would like to request support for the creation of a Mattermost plugin.

I understand this might be low priority for the Botpress Team, but maybe you could reference documentation or a tutorial to support a contribution for Mattermost and similar messaging vendors?

**Comment by J-FMartin** [comment]
Bonjour @JustusNBB and thanks for this. As previously mentioned, Mattermost is not on our roadmap. If you would like to contribute, please reference this document: https://github.com/botpress/botpress/blob/master/.github/CONTRIBUTING.md

Thanks again.

**Comment by JustusNBB** [comment]
> please reference this document: https://github.com/botpress/botpress/blob/master/.github/CONTRIBUTING.md

I read and know that one, but I have not found anything related to messaging in that document! I was requesting references to example implementations (which I guess are not to difficult to find in this repo here now). It would be great to have some guiding docs for this new messaging service. I thought that was the idea, to be extendable for integration into any messaging platform?
