### ISSUE TITLE
Migration failure - conversations

### ISSUE THREAD

**Issue by allardy** [botpress/messaging#28]
The migration seems a bit flaky, we can expect invalid entries in the database, and it should be able to handle it. 
I can provide my core.sqlite file if you want to try it out

![image](https://user-images.githubusercontent.com/42552874/126389200-f461e5b9-cd40-4a56-ad9e-02abc2e922e5.png)

**Comment by samuelmasse** [comment]
This is fixed. It was caused by some problems with how visitorIds where treated and deleted bots being ingnored
