### ISSUE TITLE
[BUG] Error message not clear

### ISSUE THREAD

**Issue by allardy** [botpress/messaging#346]
When I speak to my bot, I get this error message continuously. I have no idea how to debug that, I tried to add `LOGGING_ENABLED: true` in `messaging-server`, but it didn't help.

Previously I would just add some logging in messaging source code, build it, then set DEV_MESSAGING_PATH, but it doesn't work since the migration to node 16 (which supports natively optional chaining, while 12 doesnT). How do you develop and debug currently? 
![image](https://user-images.githubusercontent.com/42552874/153352487-23edc8d1-0815-442c-90d4-6304218a006f.png)

**Comment by samuelmasse** [comment]
Adding logging in messaging is not going to make this error message any clearer. The @botpress/messaging-client package doesn't log it's errors to the console so we'll add that

**Comment by laurentlp** [comment]
Fixed with https://github.com/botpress/messaging/pull/351
