### ISSUE TITLE
Sending video type, File type and location type not working on Telegram

### ISSUE THREAD

**Issue by gaurav-amnil** [botpress/messaging#362]
Hello,

I can see checked checkbox for `video` type, `file` type and `location` type.
 on https://github.com/botpress/messaging/tree/master/packages/channels/src/telegram
 
 But, I'm unable to receive any of these types on `telegram`.
 It is working as expected on web channel.
 Does it need extra configuration or is it a bug?

**Comment by J-FMartin** [comment]
Hi - please file these questions on our forum here: https://github.com/botpress/botpress/discussions
