### ISSUE TITLE
Database error crashes the server

### ISSUE THREAD

**Issue by allardy** [botpress/messaging#38]
At first I had a missing field error which crashed the whole app
![image](https://user-images.githubusercontent.com/42552874/126662619-43900c4e-d277-4748-a72d-ac92ba935704.png)

After adding the field, it crashed again for another reason...
![image](https://user-images.githubusercontent.com/42552874/126662522-d131aa23-7ef5-4f14-8fa3-0cd7dc00164b.png)

I had to manually go delete the entry from the database... Please make this more reliable and error-resistant. Such errors can happen and should NOT crash the whole server

**Comment by samuelmasse** [comment]
You just started the server from an old indev version. There isn't a migration to upgrade from an indev version to another. Just delete your database

**Comment by allardy** [comment]
That's not the issue. Errors should be logged and the server must remain up and running. How are you going to investigate an issue if the server keeps restarting and when you don't have access to server logs ??

**Comment by samuelmasse** [comment]
You did not solve any issue by adding the bot field. Just delete your database. The unique constraint has moved from unique visitorId to unique visitorId + botId which is why you got the second error.

**Comment by allardy** [comment]
Yes, I know. I deleted the table and the issue was fixed. 

I still think that the error shouldn't have crashed the server. Please add an error handler and print logs (with attached stack traces) instead of crashing.

**Comment by laurentlp** [comment]
Fixed here: https://github.com/botpress/botpress/pull/5167/commits/f6414005adab6a694de9776522edf48e80e693e1
