### ISSUE TITLE
Too many stack traces when an error occurs

### ISSUE THREAD

**Issue by allardy** [botpress/messaging#39]
I got this error message when my server restarted while discussing with the bot on slack. This log is way too long (axios traces of like 300 lines). Please just print the error message, or pick useful stuff from the axios error and only display that

![image](https://user-images.githubusercontent.com/42552874/126663016-f4eef985-6681-4e56-833d-b9771f7bad9c.png)

On a side note, shouldn't it write [Messaging] Channel-Slack instead of "launcher" ?

**Comment by samuelmasse** [comment]
Fixed I put a try catch there and I only print error.message
