### ISSUE TITLE
[BUG] Problem with custom URL as callback

### ISSUE THREAD

**Issue by allardy** [botpress/messaging#397]
On Botpress you can configure the base URL to something different than / and it looks like messaging is not taking this into account. 
There are often users who changes that to /botpress, so it changes the base url of the whole server, so it would be http://localhost:3000/botpress/api/v1/chat/receive

![image](https://user-images.githubusercontent.com/42552874/156222475-6b995d7c-1081-4ac1-889f-eaefe22e3270.png)

**Comment by samuelmasse** [comment]
https://github.com/botpress/botpress/pull/11574
