### ISSUE TITLE
Misleading error message when messaging is down

### ISSUE THREAD

**Issue by allardy** [botpress/messaging#43]
When messaging has crashed and will not start again, the error message displayed is a bit misleading. 

What do you think writing "Messaging service unavailable" instead ? 

![image](https://user-images.githubusercontent.com/42552874/126672053-ee967f13-f49e-4395-a205-7d5f2921eb39.png)

**Comment by samuelmasse** [comment]
Messaging pretty much can't crash anymore. The worst it will do is return 500 internal error and keep running. So this isn't really a concern
