### ISSUE TITLE
Converse API crashes the server

### ISSUE THREAD

**Issue by allardy** [botpress/messaging#45]
Not sure how to reproduce, but a missing conversationId causes the whole server to restart

![image](https://user-images.githubusercontent.com/42552874/126684219-968d813b-32ae-4c2d-bece-dcb42f7d4564.png)

**Comment by allardy** [comment]
Ok, found the source. Simply making a call using converse crashes the server. There is no thread ID when using converse.

**Comment by samuelmasse** [comment]
Fixed
