### ISSUE TITLE
Spammed by error messages when invalid config

### ISSUE THREAD

**Issue by allardy** [botpress/messaging#68]
Starting up my server with invalid config causes BP to spam this error message every 15 seconds

![image](https://user-images.githubusercontent.com/42552874/127687494-dd218457-6361-4e9b-94c1-92e7d347d195.png)

**Comment by allardy** [comment]
Also, both error messages are not helpful.  I have no idea why messenger fails. As for telegram, there is a mention of an HTTPS url, but there's no URL to configure in channel-messenger, and nowhere is it explained that that URL is built from the external_url parameter

**Comment by samuelmasse** [comment]
It's explained in the documentation for all channels that you need to configure an https endpoint to your botpress server before setting up the channel.
