### ISSUE TITLE
Migration issue

### ISSUE THREAD

**Issue by allardy** [botpress/messaging#83]
I set up all channels on the previous version, then copied my data folder over to master, and started it. I had those issues. I couldn't test smooch because I don't have an account, but I hope it will be tested

1. Telegram was working fine in the previous version, but it doesn't work anymore after the migration. I don't use a standard port, but it should still work fine, can you use the same version/setup that was used by channel-telegram so the migration is seamless? 
![image](https://user-images.githubusercontent.com/42552874/128398138-da98cd38-1a13-453c-9e61-bf0c2a352d6a.png)

4. Smooch fails on the first startup after the migration and requires to be rebooted again to start working
![image](https://user-images.githubusercontent.com/42552874/128400909-551b8cc0-60dd-4532-9114-c61a07a273e0.png)

5. Migrations are executed after modules are loaded, which generates a ton of error messages... Is there a better way we could handle this ? 
![image](https://user-images.githubusercontent.com/42552874/128397941-8bdf4d26-1b51-4005-add9-a9ec12d5af7e.png)

**Comment by samuelmasse** [comment]
1. That's because we removed polling from telegram because it doesn't allow lazy loading. What we could do is put back polling for telegram when messaging is spinned and when CLUSTER_ENABLED is set to false.

2. That's a weird one. It looks like smooch accept recreating an existing webhooks except for when you try to recreate it for the first time. Should be solvable by fetching the webhook first.

3. Not sure @laurentlp what do you think? We could maybe hardcode these channels not to produce errors somewhere but it would be a bit dirty...

**Comment by laurentlp** [comment]
> 3. Not sure @laurentlp what do you think? We could maybe hardcode these channels not to produce errors somewhere but it would be a bit dirty...

@allardy Do you think it would be possible to run migrations (or some migrations) before loading the modules?

**Comment by samuelmasse** [comment]
1. Is fixed in #99

**Comment by samuelmasse** [comment]
2. Fixed here #100

**Comment by allardy** [comment]
> > 1. Not sure @laurentlp what do you think? We could maybe hardcode these channels not to produce errors somewhere but it would be a bit dirty...
> 
> @allardy Do you think it would be possible to run migrations (or some migrations) before loading the modules?

Not really, since you need to load all migrations (core + each modules), order them, then execute them in the right order. You can't just execute all core migrations, then load modules, then  execute the remaining migrations, i'm sure something will break somewhere

**Comment by samuelmasse** [comment]
@allardy Besides having "Module not found" error to the console it doesn't seem like there should be any other problem.

**Comment by laurentlp** [comment]
@allardy @samuelmasse The alternative would be to keep the modules folders and delete them using the migrations, but it's kind of hackish so you don't have errors in the console.

**Comment by laurentlp** [comment]
3. Fixed here https://github.com/botpress/botpress/pull/5283
