### ISSUE TITLE
Migration Issue: Teams

### ISSUE THREAD

**Issue by allardy** [botpress/messaging#84]
Migration went fine while using the old URL, but as soon as I use the URL that messaging recommends me, Teams doesn't work anymore.

I changed it from `/api/v1/bots/welcome-bot/mod/channel-teams/api/messages` to `/api/v1/messaging/webhooks/welcome-bot/teams` then I started getting these error messages:

![image](https://user-images.githubusercontent.com/42552874/128402206-fa7884e9-347b-4ae7-9b59-f58a9b82a20c.png)

**Comment by samuelmasse** [comment]
It turns out this is a problem with the kvs when using sqlite. The json was being properly handled we the key was set for the first time. However the json wasn't parsed correctly when updating the key so it would put invalid values inside the db.

Fixed here :
