### ISSUE TITLE
Migration Issue: Twilio

### ISSUE THREAD

**Issue by allardy** [botpress/messaging#85]
Twilio was working fine before the migration, but now it says that the token is invalid, but the configuration in the bot config looks fine, so maybe it's a setup issue
![image](https://user-images.githubusercontent.com/42552874/128398272-9da4554b-92df-422d-81f0-723ab12a2459.png)

**Comment by samuelmasse** [comment]
@laurentlp We removed the BOT_URL env var to validate old webhooks. I think the new solution might not be working

**Comment by samuelmasse** [comment]
Fixed by #94
