### ISSUE TITLE
Migration Issue: Messenger

### ISSUE THREAD

**Issue by allardy** [botpress/messaging#86]
Messenger was working fine but stopped working after the migration
![image](https://user-images.githubusercontent.com/42552874/128398739-ea3c1777-0239-475f-800e-fc67ae518588.png)

**Comment by samuelmasse** [comment]
It looks like your webhook was configured to call ____ as a botId? Are you sure this was working before?

**Comment by allardy** [comment]
Yes, I enabled all channels on the previous BP version. I made sure they all worked properly. Then I moved my data folder and .env file over to master, started the server, and I had like half channels which were not working anymore. If you check on messenger, we did print the webhook with `___`, so we need to handle that case so the migration is non-breaking

![image](https://user-images.githubusercontent.com/42552874/128770323-1094e111-286b-42a2-b5be-86453c853aaa.png)

**Comment by samuelmasse** [comment]
Fixed here #110. It turns out botpress accepted anything as a botId when making requests to messenger. After that bots were identified with the pageId not the webhook url, so I had to write some legacy handling in the messenger channel.
